### ISSUE TITLE
Update ActiveMerchant

### ISSUE THREAD

**Issue by bb-dagher41** [killbill/killbill-litle-plugin#14]
The test and live url's that the current version of ActiveMerchant uses are no longer valid. The ActiveMerchant repository has updated this on their end, this plugin however would need to update to the a more recent version to resolve this.

**Comment by pierre** [comment]
URLs can already be configured in the global configuration (YAML file), see https://github.com/killbill/killbill-plugin-framework-ruby/blob/e789d92f2253d3a28e596321fad9a6720592584e/lib/killbill/helpers/active_merchant/gateway.rb#L18-L20.

Note also that we likely won't upgrade ActiveMerchant anymore but instead fork it as necessary (see https://github.com/killbill/killbill-litle-plugin/blob/HEAD/lib/litle.rb -- we do the same in other plugins too, such as [CyberSource](https://github.com/killbill/killbill-cybersource-plugin/blob/master/lib/cybersource/ext/active_merchant/active_merchant.rb)).

In the future, please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).

**Comment by bb-dagher41** [comment]
Thanks @pierre I'm kind of new to the killbill eco-system.
